import xml.etree.ElementTree as ET


def polynomial_exponents(dimension: int, max_order: int):
    if dimension == 0:
        yield ()
        return

    for i in range(max_order + 1):
        for tail in polynomial_exponents(dimension - 1, max_order - i):
            yield (i,) + tail


def generate_poly_evaluator(n_dof: int, order: int) -> tuple[str, str]:
    """
    Generates straight-line Warp code for evaluating a multivariate polynomial
    and its partial derivatives, using itertools for exponent ordering.
    """
    function_name = f"evaluate_polynomial_dimension{n_dof}_order{order}"
    lines = []
    lines.append(f"@wp.func")
    lines.append(f"def {function_name}(")
    lines.append(f"        coefficients: wp.array(dtype=float),")
    lines.append(f"        q_pows: types.PolyPowCache,")
    lines.append(f"        start_idx: int,")
    lines.append(f") -> tuple[float, types.PolyVec]:")
    lines.append(f"    length = float(0.0)")
    lines.append(f"    df_dq = types.PolyVec(0.0)")
    lines.append("")

    # Iterate through the generated exponents
    for coeff_idx, powers in enumerate(polynomial_exponents(n_dof, order)):
        c_str = f"coefficients[start_idx + {coeff_idx}]"
        lines.append(f"    # Coefficient {coeff_idx}: Exponents {powers}")

        # 1. Function Evaluation (Skip terms where power is 0)
        term_factors = [c_str]
        for dof, p in enumerate(powers):
            if p > 0:
                term_factors.append(f"q_pows[{dof}, {p}]")

        lines.append(f"    length += {' * '.join(term_factors)}")

        # 2. Partial Derivatives (dL/dq)
        for dof, p in enumerate(powers):
            if p > 0:
                # Derivative of q^p is p * q^(p-1)
                deriv_factors = [c_str, str(float(p))]
                for i, p_i in enumerate(powers):
                    if i == dof:
                        if p_i - 1 > 0:
                            deriv_factors.append(f"q_pows[{i}, {p_i - 1}]")
                    else:
                        if p_i > 0:
                            deriv_factors.append(f"q_pows[{i}, {p_i}]")

                lines.append(f"    df_dq[{dof}] += {' * '.join(deriv_factors)}")

        lines.append("")  # Blank line for readability

    lines.append("    return length, df_dq")

    return function_name, "\n".join(lines)


def collect_necessary_dim_order(file):
    with open(file, 'r') as file:
        tree = ET.parse(file)
    root = tree.getroot()
    function_path_set = root.find("Set_FunctionBasedPath_")
    objects = function_path_set.find("objects")
    dim_order = []
    for fn in objects:
        length_fn = fn.find("length_function")
        poly = length_fn.find("MultivariatePolynomialFunction")
        dimension = int(poly.find("dimension").text)
        order = int(poly.find("order").text)
        dim_order.append((dimension, order))

    dim_order = set(dim_order)
    return dim_order


def main():
    # Add more as needed
    dim_order = [
        (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9),
        (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9),
        (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9),
        (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9),
        (5, 4),
        (6, 4),
        (7, 4),
        (8, 4),
        (9, 4),
        (10, 4),
        (12, 4),
    ]

    functions = {}

    # Generate the functions
    for (dimension, order) in dim_order:
        number_terms = len(list(polynomial_exponents(dimension, order)))
        print(f"Compiling polynomial evaluator for dimension {dimension} and order {order}. Num terms: {number_terms}")
        function_name, generated_function = generate_poly_evaluator(dimension, order)
        functions[(dimension, order)] = (function_name, generated_function)

    # Write to file
    output_file = "polynomial_evaluator.py"
    with open(output_file, 'w') as file:
        file.write("# @generated \n")
        file.write("# --- This file is autogenerated --- #\n")
        file.write("import warp as wp\n")
        file.write("from . import types\n")
        file.write("SUPPORTED_DIM_ORDER = [")
        for (dimension, order) in dim_order:
            file.write(f"({dimension}, {order}), ")
        file.write("]\n")
        file.write("\n\n")

        for (_, function) in functions.values():
            file.write(function)
            file.write("\n\n")

        # Main entry point
        file.write("@wp.func\n")
        file.write("def evaluate_polynomial(\n")
        file.write("    coefficients: wp.array(dtype=float),\n")
        file.write("    q_pows: types.PolyPowCache,\n")
        file.write("    start_idx: int,\n")
        file.write("    order: int,\n")
        file.write("    dimension: int,\n")
        file.write(") -> tuple[float, types.PolyVec]:\n")

        flag = True
        for (dimension, order), (function_name, _) in functions.items():
            if flag:
                file.write(f"\tif dimension == {dimension} and order == {order}:\n")
                flag = False
            else:
                file.write(f"\telif dimension == {dimension} and order == {order}:\n")
            file.write(f"\t\treturn {function_name}(coefficients, q_pows, start_idx)\n")
        file.write("\treturn 0.0, types.PolyVec(0.0)\n")


if __name__ == "__main__":
    main()
